  platform :ios, '9.0'
  use_frameworks!

target 'GoliathNationalBank' do
    pod 'Alamofire'
  end

  target 'GoliathNationalBankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoliathNationalBankUITests' do
    inherit! :search_paths
    # Pods for testing
  end


